version: 0.2

env:
  secrets-manager:
      creds: "sampler"

phases:
  build:
    commands:
       - sudo apt-get update
       - sudo apt-get install python3-virtualenv -y
       - python3 -m venv automated-test-venv
       - . automated-test-venv/bin/activate
       - pip3 install playwright pytest pytest-playwright
       - playwright install
       - pytest --junitxml=reports/results.xml

reports:
  pytest-report:
    base-directory: reports
    files:
      - "results.xml"
    file-format: "JUNITXML" 